#!/bin/bash
# schwarm: Generates .planning/STATE.md dashboard from GitHub Issues
# Usage: bash sync-state.sh
# Requires: gh CLI authenticated, git repo
# Reads stream names from .schwarm.json (falls back to: backend, frontend)

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# Fail fast if gh CLI not authenticated
if ! gh auth status >/dev/null 2>&1; then
  echo "ERROR: gh CLI not authenticated. Run 'gh auth login' first." >&2
  exit 1
fi

# Load streams from .schwarm.json or use defaults
if [ -f ".schwarm.json" ]; then
  STREAMS=$(python3 -c "import json; c=json.load(open('.schwarm.json')); print(' '.join(s['name'] for s in c.get('streams',[])))" 2>/dev/null)
fi
STREAMS=${STREAMS:-"backend frontend"}

STATE=".planning/STATE.md"
mkdir -p .planning

cat > "$STATE" << 'HEADER'
---
auto_generated: true
---

# Project State

> Auto-generated by schwarm plugin. Do not edit manually.
> GSD phases: use `/gsd:progress`. Streams: use `/schwarm:dashboard`.

HEADER

echo "## Active Streams" >> "$STATE"
echo "" >> "$STATE"
echo "| Stream | Open | Ready | Blocked |" >> "$STATE"
echo "|--------|------|-------|---------|" >> "$STATE"

for stream in $STREAMS; do
  total=$(gh issue list -l "stream:$stream" -s open --json number | python3 -c "import json,sys;print(len(json.load(sys.stdin)))" || { echo "ERROR: Failed to fetch stream:$stream issues" >&2; echo "ERR"; })
  ready=$(gh issue list -l "stream:$stream" -l "status:ready" -s open --json number | python3 -c "import json,sys;print(len(json.load(sys.stdin)))" || echo "0")
  blocked=$(gh issue list -l "stream:$stream" -l "status:blocked" -s open --json number | python3 -c "import json,sys;print(len(json.load(sys.stdin)))" || echo "0")
  echo "| $stream | $total | $ready | $blocked |" >> "$STATE"
done

# Shared code status (configurable via .schwarm.json)
SHARED_DIR=""
if [ -f ".schwarm.json" ]; then
  SHARED_DIR=$(python3 -c "import json; c=json.load(open('.schwarm.json')); print(c.get('sharedDir',''))" 2>/dev/null || echo "")
fi
if [ -z "$SHARED_DIR" ]; then
  for candidate in packages/shared/src packages/shared src/shared lib/shared; do
    if [ -d "$candidate" ]; then SHARED_DIR="$candidate"; break; fi
  done
fi
if [ -n "$SHARED_DIR" ] && [ -d "$SHARED_DIR" ]; then
  echo "" >> "$STATE"
  echo "## Shared Code" >> "$STATE"
  echo "" >> "$STATE"
  echo "Last change: $(git log -1 --format='%ci (%s)' -- "$SHARED_DIR" 2>/dev/null || echo 'no changes tracked')" >> "$STATE"
fi

echo "" >> "$STATE"
echo "## Stream Backlogs" >> "$STATE"

for stream in $STREAMS; do
  echo "" >> "$STATE"
  echo "### stream:$stream" >> "$STATE"
  gh issue list -l "stream:$stream" -s open --limit 10 --json number,title 2>/dev/null | python3 -c "
import json,sys
for i in json.load(sys.stdin):
    print(f'- [ ] #{i[\"number\"]} {i[\"title\"]}')
" >> "$STATE" 2>/dev/null || echo "- (no issues)" >> "$STATE"
done

echo "" >> "$STATE"
echo "---" >> "$STATE"
echo "_Last synced: $(date -u +%Y-%m-%dT%H:%M:%SZ)_" >> "$STATE"

echo "STATE.md regenerated ($(wc -l < "$STATE" | tr -d ' ') lines)"
